<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
<name>AdvancedSplitPage</name>
<message>
<source>Off</source>
<translation>Выкл.</translation>
</message>
</context>
<context>
<name>AlarmClockFreq</name>
<message>
<source>always</source>
<translation>Всегда</translation>
</message>
<message>
<source>mon-fri</source>
<translation>пон-пят</translation>
</message>
<message>
<source>once</source>
<translation>однажды</translation>
</message>
<message>
<source>sat-sun</source>
<translation>суб-воскр</translation>
</message>
</context>
<context>
<name>AlarmClockTimeFreq</name>
<message>
<source>Fri</source>
<translation>Пт</translation>
</message>
<message>
<source>Mon</source>
<translation>Пн</translation>
</message>
<message>
<source>Sat</source>
<translation>Сб</translation>
</message>
<message>
<source>Set TimeHour &amp; MinuteDay</source>
<translation>Задать время\nЧасы и минуты\nДень</translation>
</message>
<message>
<source>Sun</source>
<translation>Вс</translation>
</message>
<message>
<source>Thu</source>
<translation>Чт</translation>
</message>
<message>
<source>Tue</source>
<translation>Вт</translation>
</message>
<message>
<source>Wake up</source>
<translation>Будильник</translation>
</message>
<message>
<source>Wed</source>
<translation>Ср</translation>
</message>
</context>
<context>
<name>AlarmList</name>
<message>
<source>Alarm type</source>
<translation>Тип сигнализации</translation>
</message>
<message>
<source>Alarms</source>
<translation>Сигналы</translation>
</message>
<message>
<source>Date &amp; Hour</source>
<translation>Дата и время</translation>
</message>
<message>
<source>Zone</source>
<translation>Зона</translation>
</message>
</context>
<context>
<name>AlertMessagePage</name>
<message>
<source>Messages</source>
<translation>Сообщения</translation>
</message>
<message>
<source>New Message</source>
<translation>Новое сообщение</translation>
</message>
</context>
<context>
<name>Antintrusion</name>
<message>
<source>anti-panic</source>
<translation>срочный вызов</translation>
</message>
<message>
<source>intrusion</source>
<translation>Вторжение</translation>
</message>
<message>
<source>tamper</source>
<translation>самозащита</translation>
</message>
<message>
<source>technical</source>
<translation>технич.тревога</translation>
</message>
<message>
<source>Z%1</source>
<translation>Z%1</translation>
</message>
</context>
<context>
<name>AudioPlayerPage</name>
<message>
<source> </source>
<translation></translation>
</message>
<message>
<source>
Information not available</source>
<translation>
Информация недоступна</translation>
</message>
<message>
<source>
Loading...</source>
<translation>
Загружается…</translation>
</message>
<message>
<source>
Track: %1 / %2</source>
<translation>
Дорожка: %1 / %2</translation>
</message>
<message>
<source>
Volume</source>
<translation>
Громкость</translation>
</message>
</context>
<context>
<name>
BrightnessPage</name>
<message>
<source>
Brightness</source>
<translation>
Яркость</translation>
</message>
</context>
<context>
<name>
CalibrationWidget</name>
<message>
<source>
Click the crosshair</source>
<translation>
Нажмите crosshair</translation>
</message>
<message>
<source>
Click the OK button</source>
<translation>
Нажмите кнопку ОК</translation>
</message>
</context>
<context>
<name>
call_notifier</name>
<message>
<source>
Door lock</source>
<translation>
Замок</translation>
</message>
<message>
<source>
Staircase light</source>
<translation>
Свет лестница</translation>
</message>
<message>
<source>
Unknown</source>
<translation>
Неизвестный</translation>
</message>
</context>
<context>
<name>
DeleteMessagesPage</name>
<message>
<source>
Are you sure to delete all messages?</source>
<translation>
Вы действительно хотите удалить все сообщения?</translation>
</message>
<message>
<source>
Messages</source>
<translation>
Сообщения</translation>
</message>
</context>
<context>
<name>
DeviceConditionDisplayDimming</name>
<message>
<source>
OFF</source>
<translation>
OFF</translation>
</message>
</context>
<context>
<name>
DeviceConditionDisplayOnOff</name>
<message>
<source>
OFF</source>
<translation>
OFF</translation>
</message>
<message>
<source>
ON</source>
<translation>
ON</translation>
</message>
</context>
<context>
<name>
DeviceConditionDisplayVolume</name>
<message>
<source>
OFF</source>
<translation>
OFF</translation>
</message>
<message>
<source>
ON</source>
<translation>
ON</translation>
</message>
</context>
<context>
<name>
EditEnergyCost</name>
<message>
<source>
Consumption</source>
<translation>
Потребление</translation>
</message>
<message>
<source>
DHW</source>
<translation>
Снабжение горячей водой</translation>
</message>
<message>
<source>
Electricity</source>
<translation>
Электричество</translation>
</message>
<message>
<source>
Gas</source>
<translation>
Газ</translation>
</message>
<message>
<source>
Heating/Cooling</source>
<translation>
Отопление / охлаждение</translation>
</message>
<message>
<source>
Production</source>
<translation>
Производство</translation>
</message>
<message>
<source>
Water</source>
<translation>
Вода</translation>
</message>
</context>
<context>
<name>
EnergyView</name>
<message>
<source>
/days</source>
<translation>
/дней</translation>
</message>
<message>
<source>
/hours</source>
<translation>
/часов</translation>
</message>
<message>
<source>
/months</source>
<translation>
/месяцев</translation>
</message>
<message>
<source>
Cumulative</source>
<translation>
Накопительная</translation>
</message>
<message>
<source>
Current</source>
<translation>
Текущая</translation>
</message>
<message>
<source>
Daily Average</source>
<translation>
Среднедневная</translation>
</message>
<message>
<source>
Day</source>
<translation>
День</translation>
</message>
<message>
<source>
Hour</source>
<translation>
Час</translation>
</message>
<message>
<source>
Month</source>
<translation>
Месяц</translation>
</message>
</context>
<context>
<name>
HandsFree</name>
<message>
<source>
Hands Free</source>
<translation>
Свободные руки</translation>
</message>
</context>
<context>
<name>
impPassword</name>
<message>
<source>
Check password:</source>
<translation>
Проверить пароль:</translation>
</message>
<message>
<source>
New password:</source>
<translation>
Новый пароль:</translation>
</message>
<message>
<source>
Old password:</source>
<translation>
Старый пароль:</translation>
</message>
<message>
<source>
Verify password:</source>
<translation>
Проверить пароль:</translation>
</message>
</context>
<context>
<name>
InfoPage</name>
<message>
<source>
Address N.</source>
<translation>
Адрес внутр.бл.</translation>
</message>
<message>
<source>
Firmware version</source>
<translation>
ВЕРСИИ ПРОШИВКИ</translation>
</message>
<message>
<source>
Kernel version</source>
<translation>
Версия ядра</translation>
</message>
<message>
<source>
Model</source>
<translation>
Модель</translation>
</message>
<message>
<source>
T.S. N.</source>
<translation>
№ T.S. </translation>
</message>
</context>
<context>
<name>
Keypad</name>
<message>
<source>
PASSWORD:</source>
<translation>
ПАРОЛЬ:</translation>
</message>
<message>
<source>
Wrong password</source>
<translation>
Неверный пароль</translation>
</message>
</context>
<context>
<name>
LanSettings</name>
<message>
<source>
Connection Status</source>
<translation>
Состояние соединения</translation>
</message>
<message>
<source>
DNS</source>
<translation>
DNS</translation>
</message>
<message>
<source>
Down</source>
<translation>
Вниз</translation>
</message>
<message>
<source>
Gateway</source>
<translation>
Портал</translation>
</message>
<message>
<source>
IP</source>
<translation>
IP</translation>
</message>
<message>
<source>
Mac</source>
<translation>
Mac</translation>
</message>
<message>
<source>
Subnet mask</source>
<translation>
Маска подсети</translation>
</message>
<message>
<source>
Up</source>
<translation>
Вверх</translation>
</message>
</context>
<context>
<name>
LoadDataContent</name>
<message>
<source>
date/time</source>
<translation>
ДАТА/ВРЕМЯ</translation>
</message>
</context>
<context>
<name>
LoadDataPage</name>
<message>
<source>
Text-Confirm-LoadDataPage</source>
<translation>
Сохраненные данные будут удалены.\nOK для подтверждения.</translation>
</message>
</context>
<context>
<name>
MessagePage</name>
<message>
<source>
Messages</source>
<translation>
Сообщения</translation>
</message>
<message>
<source>
New Message</source>
<translation>
Новое сообщение</translation>
</message>
</context>
<context>
<name>
MessagesListPage</name>
<message>
<source>
Messages</source>
<translation>
Сообщения</translation>
</message>
</context>
<context>
<name>
MultimediaFileListPage</name>
<message>
<source>
Folder</source>
<translation>
Папка</translation>
</message>
</context>
<context>
<name>
PageManual</name>
<message>
<source>
Manual</source>
<translation>
Ручной</translation>
</message>
</context>
<context>
<name>
PowerAmplifierPage</name>
<message>
<source>
Balance</source>
<translation>
Баланс</translation>
</message>
<message>
<source>
Bass</source>
<translation>
Низкие</translation>
</message>
<message>
<source>
Loud</source>
<translation>
Громко</translation>
</message>
<message>
<source>
Treble</source>
<translation>
Высокие</translation>
</message>
</context>
<context>
<name>
PowerAmplifierPreset</name>
<message>
<source>
Classical</source>
<translation>
Классический</translation>
</message>
<message>
<source>
Dance</source>
<translation>
Танцевальный</translation>
</message>
<message>
<source>
Full Bass</source>
<translation>
Низкие</translation>
</message>
<message>
<source>
Full Treble</source>
<translation>
Высокие</translation>
</message>
<message>
<source>
Normal</source>
<translation>
Нормальный</translation>
</message>
<message>
<source>
Party</source>
<translation>
Вечеринка</translation>
</message>
<message>
<source>
Pop</source>
<translation>
Поп</translation>
</message>
<message>
<source>
Rock</source>
<translation>
Рок</translation>
</message>
<message>
<source>
Soft</source>
<translation>
Спокойный</translation>
</message>
<message>
<source>
Techno</source>
<translation>
Техно</translation>
</message>
<message>
<source>
User</source>
<translation>
Пользователь</translation>
</message>
</context>
<context>
<name>
ProbesPage</name>
<message>
<source>
Temperature</source>
<translation>
Температура</translation>
</message>
<message>
<source>
Zone</source>
<translation>
Датчик</translation>
</message>
</context>
<context>
<name>
ProfessionalStudio</name>
<message>
<source>
Professional studio</source>
<translation>
Профессиональная студия</translation>
</message>
</context>
<context>
<name>
RadioInfo</name>
<message>
<source>
Channel: %1</source>
<translation>
Канал: %1</translation>
</message>
<message>
<source>
FM %1</source>
<translation>
FM %1</translation>
</message>
</context>
<context>
<name>
RadioPage</name>
<message>
<source>
RDS Radio</source>
<translation>
Радио RDS </translation>
</message>
</context>
<context>
<name>
RingExclusion</name>
<message>
<source>
Ring exclusion</source>
<translation>
Отключение звонка</translation>
</message>
</context>
<context>
<name>
ScenEvoManager</name>
<message>
<source>
Time ConditionsHour &amp; Minute</source>
<translation>
Условия времени\nЧасы и минуты</translation>
</message>
</context>
<context>
<name>
ScreenSaverPage</name>
<message>
<source>
Balls</source>
<translation>
Шарики</translation>
</message>
<message>
<source>
Line</source>
<translation>
Линия</translation>
</message>
<message>
<source>
No screensaver</source>
<translation>
Нет заставки экрана</translation>
</message>
<message>
<source>
Slideshow</source>
<translation>
Слайд-шоу</translation>
</message>
<message>
<source>
Slideshow timeout</source>
<translation>
Тайм-аут слайд-шоу</translation>
</message>
<message>
<source>
Text</source>
<translation>
Текст</translation>
</message>
<message>
<source>
Time</source>
<translation>
Час</translation>
</message>
</context>
<context>
<name>
ScreensaverTiming</name>
<message>
<source>
 sec</source>
<translation>
с</translation>
</message>
</context>
<context>
<name>
SlideshowSelector</name>
<message>
<source>
Folder</source>
<translation>
Папка</translation>
</message>
</context>
<context>
<name>
SplitMode</name>
<message>
<source>
AUTOMATIC</source>
<translation>
Автоматически</translation>
</message>
<message>
<source>
COOLING</source>
<translation>
Охлаждение</translation>
</message>
<message>
<source>
DRY</source>
<translation>
Поглощение влаги</translation>
</message>
<message>
<source>
FAN</source>
<translation>
Вентилятор</translation>
</message>
<message>
<source>
HEATING</source>
<translation>
Отопление</translation>
</message>
<message>
<source>
OFF</source>
<translation>
OFF</translation>
</message>
</context>
<context>
<name>
SplitPage</name>
<message>
<source>
Off</source>
<translation>
Выкл.</translation>
</message>
</context>
<context>
<name>
SplitSettings</name>
<message>
<source>
SWING</source>
<translation>
Качание</translation>
</message>
</context>
<context>
<name>
SplitSpeed</name>
<message>
<source>
AUTOMATIC</source>
<translation>
Автоматически</translation>
</message>
<message>
<source>
HIGH</source>
<translation>
Высокая</translation>
</message>
<message>
<source>
LOW</source>
<translation>
Низкая</translation>
</message>
<message>
<source>
MEDIUM</source>
<translation>
Средний</translation>
</message>
<message>
<source>
SILENT</source>
<translation>
Бесшумный</translation>
</message>
</context>
<context>
<name>
StopAndGoBTestPage</name>
<message>
<source>
Enable</source>
<translation>
Активировать</translation>
</message>
<message>
<source>
Self-test</source>
<translation>
Самоанализ</translation>
</message>
</context>
<context>
<name>
StopAndGoPage</name>
<message>
<source>
Enable</source>
<translation>
Активировать</translation>
</message>
</context>
<context>
<name>
StopAndGoPlusPage</name>
<message>
<source>
Enable</source>
<translation>
Активировать</translation>
</message>
</context>
<context>
<name>
TimePeriodSelection</name>
<message>
<source>
Last 12 months</source>
<translation>
Последние 12 месяцев</translation>
</message>
</context>
<context>
<name>
VCTCallPrivate::CameraImageControl</name>
<message>
<source>
Brightness</source>
<translation>
Яркость</translation>
</message>
<message>
<source>
Color</source>
<translation>
Цвет</translation>
</message>
<message>
<source>
Contrast</source>
<translation>
Контраст</translation>
</message>
</context>
<context>
<name>
VolumePage</name>
<message>
<source>
Volume</source>
<translation>
Громкость</translation>
</message>
</context>
<context>
<name>
WebcamListPage</name>
<message>
<source>
Webcam</source>
<translation>
Веб-камера</translation>
</message>
</context>
</TS>
