#include "bann2_buttons.h"
#include "main.h"

#include <QWidget>
#include <QLabel>


#define BAN2BUT_BUT_DIM 60
#define BUTONOFF_ICON_DIM_X 120
#define BUTONOFF_ICON_DIM_Y 60
#define BANONOFF_BUT_DIM 60
#define BUTONOFF2SCR_ICON_DIM_X 80
#define BUTONOFF2SCR_ICON_DIM_Y 60
#define BANONOFF2SCR_BUT_DIM 60


bann2But::bann2But(QWidget *parent) : banner(parent)
{
	addItem(BUT1, 0 ,(MAX_HEIGHT/NUM_RIGHE - BAN2BUT_BUT_DIM)/2 , BAN2BUT_BUT_DIM , BAN2BUT_BUT_DIM);
	addItem(BUT2, MAX_WIDTH - BAN2BUT_BUT_DIM ,(MAX_HEIGHT/NUM_RIGHE - BAN2BUT_BUT_DIM)/2 , BAN2BUT_BUT_DIM , BAN2BUT_BUT_DIM);
	addItem(TEXT, BAN2BUT_BUT_DIM , 0, MAX_WIDTH - 2*BAN2BUT_BUT_DIM , MAX_HEIGHT/NUM_RIGHE);
}


bann2ButLab::bann2ButLab(QWidget *parent) : banner(parent)
{
	addItem(BUT1, 0, 0, BAN2BUT_BUT_DIM , BAN2BUT_BUT_DIM);
	addItem(BUT2, MAX_WIDTH - BAN2BUT_BUT_DIM, 0, BAN2BUT_BUT_DIM, BAN2BUT_BUT_DIM);
	addItem(TEXT, BAN2BUT_BUT_DIM , 0, MAX_WIDTH - 2 * BAN2BUT_BUT_DIM , BAN2BUT_BUT_DIM);
	addItem(TEXT2, 0, BAN2BUT_BUT_DIM-5, MAX_WIDTH , 25);
}

QSize bann2ButLab::sizeHint() const
{
	return banner::sizeHint() + QSize(0, 20);
}



bannOnOff::bannOnOff(QWidget *parent) : banner(parent)
{
	addItem(BUT1, MAX_WIDTH-BANONOFF_BUT_DIM , 0 , BANONOFF_BUT_DIM , BANONOFF_BUT_DIM);
	addItem(BUT2, 0 , 0 , BANONOFF_BUT_DIM , BANONOFF_BUT_DIM);
	addItem(TEXT, 0 , BANONOFF_BUT_DIM , MAX_WIDTH , MAX_HEIGHT/NUM_RIGHE-BANONOFF_BUT_DIM);
	addItem(ICON, BANONOFF_BUT_DIM , 0 , BUTONOFF_ICON_DIM_X , BUTONOFF_ICON_DIM_Y);
}


bannOnOff2scr::bannOnOff2scr(QWidget *parent) : banner(parent)
{
	addItem(BUT1, 0 , 0 , BANONOFF2SCR_BUT_DIM , BANONOFF2SCR_BUT_DIM);
	addItem(BUT2, MAX_WIDTH-BANONOFF2SCR_BUT_DIM , 0 , BANONOFF2SCR_BUT_DIM , BANONOFF2SCR_BUT_DIM);
	addItem(TEXT, 0 , BANONOFF2SCR_BUT_DIM , MAX_WIDTH , MAX_HEIGHT/NUM_RIGHE-BANONOFF2SCR_BUT_DIM);
	addItem(ICON, MAX_WIDTH-BANONOFF2SCR_BUT_DIM-BUTONOFF2SCR_ICON_DIM_X , 0 , BUTONOFF2SCR_ICON_DIM_X , BUTONOFF2SCR_ICON_DIM_Y);
	addItem(TEXT2, BANONOFF2SCR_BUT_DIM ,0 ,MAX_WIDTH-2*BANONOFF2SCR_BUT_DIM-BUTONOFF2SCR_ICON_DIM_X, /*MAX_HEIGHT/NUM_RIGHE-BANONOFF2SCR_BUT_DIM */BUTONOFF2SCR_ICON_DIM_Y);
}

