#!/bin/bash
#set -x

if [ -z "$1" ] 
then
  echo
  echo -e "\t   1  ARGUMENT ARE REQUIRED"
  echo -e "\t  MACHINE"
  echo
  exit 1
fi

MACHINE=$1

if [ "$MACHINE" = "TS35" ]
then
  cd ts_3_5
  qmake CONFIG+=release ts_3_5.x11.pro
  #make clean
  make || exit 1
  cd ..
  exit 0
fi

if [ "$MACHINE" = "MMT" ]
then
  cd ts_10
  qmake CONFIG+=release ts_10.x11.pro
  make || exit 1
  cd ..
  exit 0
fi
exit 1
