#!/bin/bash
#set -x

if [ -z "$1" ]
then
  echo
  echo -e "\t   1  ARGUMENT ARE REQUIRED"
  echo -e "\t  MACHINE"
  echo
  exit 1
fi

MACHINE=$1

if [ "$MACHINE" = "TS35" ]
then
  cd ts_3_5
  mv BTouch.arm BTouch
  cp BTouch BTouch_no_strip
  $STRIP BTouch
  cp BTouch $BTWEB_APP_BIN_NO_STACKOPEN
  rm -f BTouch_qws
  touch BTouch_qws
  chmod +x BTouch_qws
  echo "#!/bin/sh

export LD_LIBRARY_PATH=/home/bticino/lib

export TSLIB_CONSOLEDEVICE=none
export TSLIB_FBDEVICE=/dev/fb0
export TSLIB_TSDEVICE=/dev/input/touchscreen0
export TSLIB_CALIBFILE=/home/bticino/cfg/extra/pointercal
export TSLIB_CONFFILE=/etc/ts.conf

export QWS_MOUSE_PROTO=Tslib
export QWS_DISPLAY=Transformed:Rot270
export POINTERCAL_FILE=/home/bticino/cfg/extra/pointercal

./bin/BTouch -qws -noswcursor &

trap \"killall BTouch; exit 0\" SIGTERM
wait
trap SIGTERM" >> BTouch_qws
  cp BTouch_qws $BTWEB_APP_BIN_NO_STACKOPEN
  cd ..
  exit 0
fi

if [ "$MACHINE" = "MMT" ]
then
  cd ts_10
  mv BTouch.arm BTouch
  cp BTouch BTouch_no_strip
  $STRIP BTouch
  cp BTouch $BTWEB_APP_BIN_NO_STACKOPEN
  rm -f BTouch_qws
  touch BTouch_qws
  chmod +x BTouch_qws
  echo "#!/bin/ettclsh" >> BTouch_qws
  echo "set env(QWS_MOUSE_PROTO) LinuxTP:/dev/ts" >> BTouch_qws
  echo "set env(POINTERCAL_FILE) /var/pointercal" >> BTouch_qws
  echo "set env(QT_PLUGIN_PATH) /lib/QTlib/plugins" >> BTouch_qws
  echo "exec bin/BTouch -qws -noswcursor &" >> BTouch_qws
  cp BTouch_qws $BTWEB_APP_BIN_NO_STACKOPEN
  cd ..
  exit 0
fi
exit 1
