<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
<name>AdvancedSplitPage</name>
<message>
<source>Off</source>
<translation>Kapalı</translation>
</message>
</context>
<context>
<name>AlarmClockFreq</name>
<message>
<source>always</source>
<translation>Her zaman</translation>
</message>
<message>
<source>mon-fri</source>
<translation>pzt-cum</translation>
</message>
<message>
<source>once</source>
<translation>bir kere</translation>
</message>
<message>
<source>sat-sun</source>
<translation>cts-pzr</translation>
</message>
</context>
<context>
<name>AlarmClockTimeFreq</name>
<message>
<source>Fri</source>
<translation>Cum</translation>
</message>
<message>
<source>Mon</source>
<translation>Pazt</translation>
</message>
<message>
<source>Sat</source>
<translation>Cumt</translation>
</message>
<message>
<source>Set TimeHour &amp; MinuteDay</source>
<translation>Süre\nSaat &amp; Dakika\nGün ayarla</translation>
</message>
<message>
<source>Sun</source>
<translation>Paz</translation>
</message>
<message>
<source>Thu</source>
<translation>Per</translation>
</message>
<message>
<source>Tue</source>
<translation>Sal</translation>
</message>
<message>
<source>Wake up</source>
<translation>Uyandır</translation>
</message>
<message>
<source>Wed</source>
<translation>Çar</translation>
</message>
</context>
<context>
<name>AlarmList</name>
<message>
<source>Alarm type</source>
<translation>Alarm tipi</translation>
</message>
<message>
<source>Alarms</source>
<translation>Alarmlar</translation>
</message>
<message>
<source>Date &amp; Hour</source>
<translation>Tarih &amp; saat</translation>
</message>
<message>
<source>Zone</source>
<translation>Alan</translation>
</message>
</context>
<context>
<name>AlertMessagePage</name>
<message>
<source>Messages</source>
<translation>İletiler</translation>
</message>
<message>
<source>New Message</source>
<translation>Yeni Mesaj</translation>
</message>
</context>
<context>
<name>Antintrusion</name>
<message>
<source>anti-panic</source>
<translation>panik önleme</translation>
</message>
<message>
<source>intrusion</source>
<translation>İzinsiz giriş</translation>
</message>
<message>
<source>tamper</source>
<translation>kurcalama</translation>
</message>
<message>
<source>technical</source>
<translation>teknik</translation>
</message>
<message>
<source>Z%1</source>
<translation>Z%1</translation>
</message>
</context>
<context>
<name>AudioPlayerPage</name>
<message>
<source> </source>
<translation></translation>
</message>
<message>
<source>
Information not available</source>
<translation>
Bilgi mevcut değil</translation>
</message>
<message>
<source>
Loading...</source>
<translation>
Yükleniyor…</translation>
</message>
<message>
<source>
Track: %1 / %2</source>
<translation>
Parça: %1 / %2</translation>
</message>
<message>
<source>
Volume</source>
<translation>
Ses seviyesi</translation>
</message>
</context>
<context>
<name>
BrightnessPage</name>
<message>
<source>
Brightness</source>
<translation>
Parlaklık</translation>
</message>
</context>
<context>
<name>
CalibrationWidget</name>
<message>
<source>
Click the crosshair</source>
<translation>
Artıya tıkla</translation>
</message>
<message>
<source>
Click the OK button</source>
<translation>
OK butonuna tıkla</translation>
</message>
</context>
<context>
<name>
call_notifier</name>
<message>
<source>
Door lock</source>
<translation>
Kapı kilidi</translation>
</message>
<message>
<source>
Staircase light</source>
<translation>
Merdiven lambası</translation>
</message>
<message>
<source>
Unknown</source>
<translation>
Bilinmeyen</translation>
</message>
</context>
<context>
<name>
DeleteMessagesPage</name>
<message>
<source>
Are you sure to delete all messages?</source>
<translation>
Tüm mesajları silmek istediğinden emin misin?</translation>
</message>
<message>
<source>
Messages</source>
<translation>
İletiler</translation>
</message>
</context>
<context>
<name>
DeviceConditionDisplayDimming</name>
<message>
<source>
OFF</source>
<translation>
OFF (KAPALI)</translation>
</message>
</context>
<context>
<name>
DeviceConditionDisplayOnOff</name>
<message>
<source>
OFF</source>
<translation>
OFF (KAPALI)</translation>
</message>
<message>
<source>
ON</source>
<translation>
ON (AÇIK)</translation>
</message>
</context>
<context>
<name>
DeviceConditionDisplayVolume</name>
<message>
<source>
OFF</source>
<translation>
OFF (KAPALI)</translation>
</message>
<message>
<source>
ON</source>
<translation>
ON (AÇIK)</translation>
</message>
</context>
<context>
<name>
EditEnergyCost</name>
<message>
<source>
Consumption</source>
<translation>
Tüketim</translation>
</message>
<message>
<source>
DHW</source>
<translation>
DHW</translation>
</message>
<message>
<source>
Electricity</source>
<translation>
Elektrik</translation>
</message>
<message>
<source>
Gas</source>
<translation>
Gaz</translation>
</message>
<message>
<source>
Heating/Cooling</source>
<translation>
Isıtma/Soğutma</translation>
</message>
<message>
<source>
Production</source>
<translation>
Üretim</translation>
</message>
<message>
<source>
Water</source>
<translation>
Su</translation>
</message>
</context>
<context>
<name>
EnergyView</name>
<message>
<source>
/days</source>
<translation>
/gün</translation>
</message>
<message>
<source>
/hours</source>
<translation>
/saat</translation>
</message>
<message>
<source>
/months</source>
<translation>
/ay</translation>
</message>
<message>
<source>
Cumulative</source>
<translation>
Kümülatif toplam</translation>
</message>
<message>
<source>
Current</source>
<translation>
Mevcut durum</translation>
</message>
<message>
<source>
Daily Average</source>
<translation>
Günlük Ortalama</translation>
</message>
<message>
<source>
Day</source>
<translation>
Gün</translation>
</message>
<message>
<source>
Hour</source>
<translation>
Saat</translation>
</message>
<message>
<source>
Month</source>
<translation>
Ay</translation>
</message>
</context>
<context>
<name>
HandsFree</name>
<message>
<source>
Hands Free</source>
<translation>
Eller Serbest</translation>
</message>
</context>
<context>
<name>
impPassword</name>
<message>
<source>
Check password:</source>
<translation>
Şifre kontrol et:</translation>
</message>
<message>
<source>
New password:</source>
<translation>
Yeni şifre:</translation>
</message>
<message>
<source>
Old password:</source>
<translation>
Eski şifre:</translation>
</message>
<message>
<source>
Verify password:</source>
<translation>
Şifre denetle:</translation>
</message>
</context>
<context>
<name>
InfoPage</name>
<message>
<source>
Address N.</source>
<translation>
İ.Ü. adresi</translation>
</message>
<message>
<source>
Firmware version</source>
<translation>
FIRMWARE VERSİYONU</translation>
</message>
<message>
<source>
Kernel version</source>
<translation>
Kernel versiyonu</translation>
</message>
<message>
<source>
Model</source>
<translation>
Model</translation>
</message>
<message>
<source>
T.S. N.</source>
<translation>
T.S. N.</translation>
</message>
</context>
<context>
<name>
Keypad</name>
<message>
<source>
PASSWORD:</source>
<translation>
ŞİFRE:</translation>
</message>
<message>
<source>
Wrong password</source>
<translation>
Şifre yanlış</translation>
</message>
</context>
<context>
<name>
LanSettings</name>
<message>
<source>
Connection Status</source>
<translation>
Bağlantı Durumu</translation>
</message>
<message>
<source>
DNS</source>
<translation>
DNS</translation>
</message>
<message>
<source>
Down</source>
<translation>
Aşağı</translation>
</message>
<message>
<source>
Gateway</source>
<translation>
Ağ geçidi</translation>
</message>
<message>
<source>
IP</source>
<translation>
IP</translation>
</message>
<message>
<source>
Mac</source>
<translation>
Mac</translation>
</message>
<message>
<source>
Subnet mask</source>
<translation>
Alt ağ maskesi</translation>
</message>
<message>
<source>
Up</source>
<translation>
Yukarı</translation>
</message>
</context>
<context>
<name>
LoadDataContent</name>
<message>
<source>
date/time</source>
<translation>
TARİH/SAAT</translation>
</message>
</context>
<context>
<name>
LoadDataPage</name>
<message>
<source>
Text-Confirm-LoadDataPage</source>
<translation>
Kaydedilmiş veriler silinecek.\nOnaylamak için OK.</translation>
</message>
</context>
<context>
<name>
MessagePage</name>
<message>
<source>
Messages</source>
<translation>
İletiler</translation>
</message>
<message>
<source>
New Message</source>
<translation>
Yeni Mesaj</translation>
</message>
</context>
<context>
<name>
MessagesListPage</name>
<message>
<source>
Messages</source>
<translation>
İletiler</translation>
</message>
</context>
<context>
<name>
MultimediaFileListPage</name>
<message>
<source>
Folder</source>
<translation>
Klasör</translation>
</message>
</context>
<context>
<name>
PageManual</name>
<message>
<source>
Manual</source>
<translation>
Manuel</translation>
</message>
</context>
<context>
<name>
PowerAmplifierPage</name>
<message>
<source>
Balance</source>
<translation>
Balans</translation>
</message>
<message>
<source>
Bass</source>
<translation>
Bass</translation>
</message>
<message>
<source>
Loud</source>
<translation>
Loud</translation>
</message>
<message>
<source>
Treble</source>
<translation>
Tiz</translation>
</message>
</context>
<context>
<name>
PowerAmplifierPreset</name>
<message>
<source>
Classical</source>
<translation>
Klasik</translation>
</message>
<message>
<source>
Dance</source>
<translation>
Dans</translation>
</message>
<message>
<source>
Full Bass</source>
<translation>
Tam Bas</translation>
</message>
<message>
<source>
Full Treble</source>
<translation>
Tam Tiz</translation>
</message>
<message>
<source>
Normal</source>
<translation>
Normal</translation>
</message>
<message>
<source>
Party</source>
<translation>
Parti</translation>
</message>
<message>
<source>
Pop</source>
<translation>
Pop</translation>
</message>
<message>
<source>
Rock</source>
<translation>
Rock</translation>
</message>
<message>
<source>
Soft</source>
<translation>
Soft</translation>
</message>
<message>
<source>
Techno</source>
<translation>
Tekno</translation>
</message>
<message>
<source>
User</source>
<translation>
Kullanıcı</translation>
</message>
</context>
<context>
<name>
ProbesPage</name>
<message>
<source>
Temperature</source>
<translation>
Sıcaklık</translation>
</message>
<message>
<source>
Zone</source>
<translation>
Sonda</translation>
</message>
</context>
<context>
<name>
ProfessionalStudio</name>
<message>
<source>
Professional studio</source>
<translation>
Mesleki büro</translation>
</message>
</context>
<context>
<name>
RadioInfo</name>
<message>
<source>
Channel: %1</source>
<translation>
Kanal: %1</translation>
</message>
<message>
<source>
FM %1</source>
<translation>
FM %1</translation>
</message>
</context>
<context>
<name>
RadioPage</name>
<message>
<source>
RDS Radio</source>
<translation>
RDS Radyo</translation>
</message>
</context>
<context>
<name>
RingExclusion</name>
<message>
<source>
Ring exclusion</source>
<translation>
Zil sesi devreden çıkarma</translation>
</message>
</context>
<context>
<name>
ScenEvoManager</name>
<message>
<source>
Time ConditionsHour &amp; Minute</source>
<translation>
Süre İklim Şartları\nSaat &amp; Dakika</translation>
</message>
</context>
<context>
<name>
ScreenSaverPage</name>
<message>
<source>
Balls</source>
<translation>
Küreler</translation>
</message>
<message>
<source>
Line</source>
<translation>
Hat</translation>
</message>
<message>
<source>
No screensaver</source>
<translation>
Ekran koruyucu yok</translation>
</message>
<message>
<source>
Slideshow</source>
<translation>
Slayt gösterisi</translation>
</message>
<message>
<source>
Slideshow timeout</source>
<translation>
Slayt gösterisi zaman aşımı</translation>
</message>
<message>
<source>
Text</source>
<translation>
Metin</translation>
</message>
<message>
<source>
Time</source>
<translation>
Saat</translation>
</message>
</context>
<context>
<name>
ScreensaverTiming</name>
<message>
<source>
 sec</source>
<translation>
 sn</translation>
</message>
</context>
<context>
<name>
SlideshowSelector</name>
<message>
<source>
Folder</source>
<translation>
Klasör</translation>
</message>
</context>
<context>
<name>
SplitMode</name>
<message>
<source>
AUTOMATIC</source>
<translation>
Otomatik</translation>
</message>
<message>
<source>
COOLING</source>
<translation>
Soğutma</translation>
</message>
<message>
<source>
DRY</source>
<translation>
Nem Giderici</translation>
</message>
<message>
<source>
FAN</source>
<translation>
Fan</translation>
</message>
<message>
<source>
HEATING</source>
<translation>
Isıtma</translation>
</message>
<message>
<source>
OFF</source>
<translation>
OFF (KAPALI)</translation>
</message>
</context>
<context>
<name>
SplitPage</name>
<message>
<source>
Off</source>
<translation>
Kapalı</translation>
</message>
</context>
<context>
<name>
SplitSettings</name>
<message>
<source>
SWING</source>
<translation>
Salınım</translation>
</message>
</context>
<context>
<name>
SplitSpeed</name>
<message>
<source>
AUTOMATIC</source>
<translation>
Otomatik</translation>
</message>
<message>
<source>
HIGH</source>
<translation>
Yüksek</translation>
</message>
<message>
<source>
LOW</source>
<translation>
Düşük</translation>
</message>
<message>
<source>
MEDIUM</source>
<translation>
Ortam</translation>
</message>
<message>
<source>
SILENT</source>
<translation>
Sessiz</translation>
</message>
</context>
<context>
<name>
StopAndGoBTestPage</name>
<message>
<source>
Enable</source>
<translation>
İzin ver</translation>
</message>
<message>
<source>
Self-test</source>
<translation>
Oto-test</translation>
</message>
</context>
<context>
<name>
StopAndGoPage</name>
<message>
<source>
Enable</source>
<translation>
İzin ver</translation>
</message>
</context>
<context>
<name>
StopAndGoPlusPage</name>
<message>
<source>
Enable</source>
<translation>
İzin ver</translation>
</message>
</context>
<context>
<name>
TimePeriodSelection</name>
<message>
<source>
Last 12 months</source>
<translation>
Son 12 ay</translation>
</message>
</context>
<context>
<name>
VCTCallPrivate::CameraImageControl</name>
<message>
<source>
Brightness</source>
<translation>
Parlaklık</translation>
</message>
<message>
<source>
Color</source>
<translation>
Renk</translation>
</message>
<message>
<source>
Contrast</source>
<translation>
Kontrast</translation>
</message>
</context>
<context>
<name>
VolumePage</name>
<message>
<source>
Volume</source>
<translation>
Ses seviyesi</translation>
</message>
</context>
<context>
<name>
WebcamListPage</name>
<message>
<source>
Webcam</source>
<translation>
Web Kamera</translation>
</message>
</context>
</TS>
