<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>sempre</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>2ª-6ª</translation>
    </message>
    <message>
        <source>once</source>
        <translation>uma vez</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sab-dom</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>antipânico</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Intrusão</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>modificação</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>técnico</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Luminosidade alta</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Luminosidade baixa</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Off</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Clique na cruz</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Clique no botão OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>luminosidade</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Calibração</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Limpe ecrã</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Protecção de ecrã</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Consumo</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Produção</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/dias</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/horas</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/meses</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Cumulativo</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Actual</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Média diária</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Dia</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Hora</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Mês</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Gateway</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Máscara sub-rede</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Álbum:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artista:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Duração:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>de</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Melodia:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balanceamento</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Baixos</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Altos</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Clássico</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dança</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Festa</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Tecno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Bolas</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Deformação</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Linha</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Não Screensaver</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Texto</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Tempo</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Rádio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Habilita</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Autoteste</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Verificação</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Últimos 12 meses</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Fechadura</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Luz escada</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Desconhecido</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
