<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>immer</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>Mon-Fr</translation>
    </message>
    <message>
        <source>once</source>
        <translation>ein Mal</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>Sam-Son</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>Antipanik</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Einbruch</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>Aufbruch</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>Technik</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Hohe Helligkeit</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Niedrige Helligkeit</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Normale Helligkeit</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Off</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Klicken Sie auf das Fadenkreuz</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Klicken Sie auf die OK-Taste</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>helligkeit</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Kalibrierung</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Bildschirm reinigen</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Bildschirmschoner</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Verbrauch</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Produktion</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/Tage</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/Stunden</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/Monate</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Kumulativ</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Aktuell</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Tagesdurchschnitt</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Tag</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Stunde</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Monat</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manuell</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Gateway</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Subnet Mask</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Künstler:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Dauer:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>von</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Musikst.:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Ausgleich</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Teif</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Hoch</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Bälle</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Lupe</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Linie</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Kein Bildschirmschoner</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Text</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Zeit</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Radio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Freigeben</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Auto Test</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Test</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Die letzten 12 Monate</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Öffnen</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Treppenlicht</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Unbekannt</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
