<!DOCTYPE TS><TS>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation type="unfinished">Clique na cruz</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation type="unfinished">Clique no botão OK</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>of</source>
        <translation>de</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Melodia:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artista:</translation>
    </message>
    <message>
        <source>Album:</source>
        <translation>Álbum:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Duração:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Altos</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Baixos</translation>
    </message>
    <message>
        <source>Balance</source>
        <translation>Balanceamento</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dança</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Classical</source>
        <translation>Clássico</translation>
    </message>
    <message>
        <source>Jazz</source>
        <translation>Jazz</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Festa</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Rádio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Self-recluser</source>
        <translation>Rearme</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Verificação</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Autoteste</translation>
    </message>
</context>
<context>
    <name>antintrusione</name>
    <message>
        <source>technical</source>
        <translation>técnico</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>intrusão</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>modificação</translation>
    </message>
    <message>
        <source>anti-panic</source>
        <translation>antipânico</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Unknown</source>
        <translation>Desconhecido</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Luzes escadas</translation>
    </message>
    <message>
        <source>Door lock</source>
        <translation>Fechadura</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>sveglia</name>
    <message>
        <source>once</source>
        <translation>uma vez</translation>
    </message>
    <message>
        <source>always</source>
        <translation>sempre</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>2ª-6ª</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sab-dom</translation>
    </message>
</context>
<context>
    <name>tastiera</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
</TS>
