<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>mindig</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>hétfő-péntek</translation>
    </message>
    <message>
        <source>once</source>
        <translation>egyszer</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>szombat-vasárnap</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>pánik elleni</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Behatolás</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>befolyás</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>műszaki</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Magas fényerősség</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Alacsony fényerősség</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Normál fényerő</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Ki</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Kattintson a célkeresztre</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Kattintson az OK gombra</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>fényerősség</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Kalibrálás</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Képernyőtisztítás</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Képernyőkímélő</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Fogyasztás</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Termelés</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/nap</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/óra</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/hónap</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Teljes fogyasztás</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Jelenlegi fogyasztás</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Napi átlag</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Nap</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Óra</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Hónap</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Kézi</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>JELSZÓ:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Átjáró</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Alhálózati maszk</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Előadó:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Hossz:</translation>
    </message>
    <message>
        <source>of</source>
        <translation></translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Dal:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balansz</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Basszus</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Mély</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Magas</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Klasszikus</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Teljes basszus</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Teljes magas</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normál</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Parti</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Előzetes beállítás</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Szoft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Labdák</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Torzítás</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Vonal</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Nincs képernyőkímélő</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Szöveg</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Idő</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP rádió</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Szerverek</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Engedélyezés</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Önellenőrzés</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Teszt</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Utolsó 12 hónap</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Ajtózár</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Lépcsőház világítás</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Ismeretlen</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
