<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="zh_TW" sourcelanguage="en">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>一直</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>週一至週五</translation>
    </message>
    <message>
        <source>once</source>
        <translation>一次</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>週六至週日</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>免驚慌</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>侵入</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>防拆</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>技術</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>高等亮度</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>低等亮度</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>正常亮度</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>關閉</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>按一下十字</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>點擊OK按鈕</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>亮度</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>校準</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>清除螢幕</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>螢幕保護程式</translation>
    </message>
</context>
<context>
    <name>EditEnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>消耗</translation>
    </message>
    <message>
        <source>DHW</source>
        <translation>DHW</translation>
    </message>
    <message>
        <source>Electricity</source>
        <translation>電</translation>
    </message>
    <message>
        <source>Gas</source>
        <translation>燃氣</translation>
    </message>
    <message>
        <source>Heating/Cooling</source>
        <translation>加熱/製冷</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>發電</translation>
    </message>
    <message>
        <source>Water</source>
        <translation>水</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/日</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/小時</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/月</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>纍加</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>當前</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>日平均</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>天</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>小時</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>月</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>手動</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>密碼:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>域名系統</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>通信閘</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>子網路遮罩</translation>
    </message>
</context>
<context>
    <name>LoadDataContent</name>
    <message>
        <source>date/time</source>
        <translation>日期/時間</translation>
    </message>
</context>
<context>
    <name>LoadDataPage</name>
    <message>
        <source>Text-Confirm-LoadDataPage</source>
        <translation type="unfinished">存儲的數據將被刪除.
確定以確認.</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>專輯:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>藝術家:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>長度:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>在</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>曲目表:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>平衡</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>低音</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>響亮</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>高音</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>古典</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>舞曲</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>重低音</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>重高音</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>正常</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>宴會</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>流行</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>搖滾</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>輕音樂</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno音樂</translation>
    </message>
    <message>
        <source>User</source>
        <translation>用戶</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>球式螢幕保護程式</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>線條</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>無螢幕保護程式</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>文字内容</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>時間</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP廣播</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>服務器</translation>
    </message>
</context>
<context>
    <name>SplitMode</name>
    <message>
        <source>COOLING</source>
        <translation>降溫</translation>
    </message>
    <message>
        <source>DRY</source>
        <translation>去濕</translation>
    </message>
    <message>
        <source>HEATING</source>
        <translation>暖氣</translation>
    </message>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
    <message>
        <source>FAN</source>
        <translation type="unfinished">風扇</translation>
    </message>
    <message>
        <source>AUTOMATIC</source>
        <translation type="unfinished">自動</translation>
    </message>
</context>
<context>
    <name>SplitSettings</name>
    <message>
        <source>SWING</source>
        <translation>擺風</translation>
    </message>
</context>
<context>
    <name>SplitSpeed</name>
    <message>
        <source>HIGH</source>
        <translation>高</translation>
    </message>
    <message>
        <source>LOW</source>
        <translation>低</translation>
    </message>
    <message>
        <source>MEDIUM</source>
        <translation>中</translation>
    </message>
    <message>
        <source>SILENT</source>
        <translation>安靜</translation>
    </message>
    <message>
        <source>AUTOMATIC</source>
        <translation type="unfinished">自動</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>啓動</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>自測</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>測試</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>最後12個月</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>門鎖</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>樓梯燈</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>未知</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>開啟</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>開啟</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>關閉</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>開啟</translation>
    </message>
</context>
</TS>
