<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>altijd</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>maan-vrij</translation>
    </message>
    <message>
        <source>once</source>
        <translation>een keer</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>za-zon</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>paniek</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Inbraak</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>sabotage</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>technisch</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Hoge helderheid</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Lage helderheid</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Normale lichtsterkte</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Off</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Klik op het kruisje</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Klik op de knop OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>lichtsterkte</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Kalibrering</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Reinig Scherm</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Screensaver</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Verbruik</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Productie</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/dagen</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/uren</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/maanden</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Cumulatief</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Huidig</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Dagelijks gemiddelde</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Dag</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Uur</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Maand</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manueel</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Gateway</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Subnet mask</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artiest:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Tijdsd.:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>van</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Tune:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balansregeling</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Lage</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Hoge</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normaal</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Ballen</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Vervorming</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Lijn</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Geen Screensaver</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Tekst</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Tijd</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Radio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Activeren</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Autotest</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Nazicht</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Laatste 12 maanden</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Slot</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Licht trapzaal</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Onbekend</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
