<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>一直</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>周一至周五</translation>
    </message>
    <message>
        <source>once</source>
        <translation>一次</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>周六至周日</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>免惊慌</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>侵入</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>防拆</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>技术</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>高等亮度</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>低等亮度</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>正常亮度</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>按一下十字</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>点击OK按钮</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>亮度</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>校准</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>清除屏幕</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>屏幕保护程序</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>消耗</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>发电</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/日</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/小时</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/月</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>累加</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>当前</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>日平均</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>天</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>小时</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>月</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>手动</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>密码:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>域名系统</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>网关</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>子网掩码</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>专辑:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>艺术家:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>长度:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>在</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>曲目表:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>平衡</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>低音</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>响亮</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>高音</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>古典</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>舞曲</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>重低音</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>重高音</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>正常</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>宴会</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>流行</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>预设</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>摇滚</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>轻音乐</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno音乐</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>球式屏幕保护程序</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>变形式屏幕保护程序</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>线条</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>无屏幕保护程序</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>文字内容</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>时间</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP广播</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>服务器</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>启动</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>自测</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>测试</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>最后12个月</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>门锁</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>楼梯灯</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>未知</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>开启</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>开启</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>开启</translation>
    </message>
</context>
</TS>
