<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>always</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>mon-fri</translation>
    </message>
    <message>
        <source>once</source>
        <translation>once</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sat-sun</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>anti-panic</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Intrusion</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>tamper</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>technical</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>High brightness</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Low brightness</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Normal brightness</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Off</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Click the crosshair</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Click the OK button</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>brightness</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Calibration</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Clean Screen</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Screen Saver</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Consumption</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Production</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/days</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/hours</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/months</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Cumulative</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Current</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Daily Average</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Day</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Hour</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Month</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Gateway</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Subnet mask</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artist:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Length:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>of</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Track:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balance</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Bass</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Treble</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Balls</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Deform</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Line</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>No Screensaver</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Text</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Time</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP radio</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Enable</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Self-test</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Test</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Last 12 months</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Door lock</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Staircase light</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Unknown</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
