<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr" sourcelanguage="en">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>toujours</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>lun-ven</translation>
    </message>
    <message>
        <source>once</source>
        <translation>une fois</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sam-dim</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>anti-panique</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Intrusion</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>sabotage</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>technique</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Luminosité élevée</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Luminosité faible</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Luminosité normale</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Off</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Cliquez sur la croix</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Cliquez sur le bouton OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>Luminosité</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Calibrage</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Nettoyer écran</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Ecran de veille</translation>
    </message>
</context>
<context>
    <name>EditEnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Consommation</translation>
    </message>
    <message>
        <source>DHW</source>
        <translation>DHW</translation>
    </message>
    <message>
        <source>Electricity</source>
        <translation>Électricité</translation>
    </message>
    <message>
        <source>Gas</source>
        <translation>Gaz</translation>
    </message>
    <message>
        <source>Heating/Cooling</source>
        <translation>Chauffage/Climatisation</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Production</translation>
    </message>
    <message>
        <source>Water</source>
        <translation>Eau</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/jours</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/heures</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/mois</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Cumulatif</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Actuel</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Moyenne journalière</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Jour</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Heure</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Mois</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manuel</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Passerelle</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Masque ss-réseau</translation>
    </message>
</context>
<context>
    <name>LoadDataContent</name>
    <message>
        <source>date/time</source>
        <translation>DATE/HEURE</translation>
    </message>
</context>
<context>
    <name>LoadDataPage</name>
    <message>
        <source>Text-Confirm-LoadDataPage</source>
        <translation type="unfinished">Les données enregistrées seront effacées.
Cliquez sur OK pour confirmer.</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Auteur:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Durée:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>de</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Morceau:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balance</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Graves</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Grave</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Aigus</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Classique</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Grave max.</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Aigus max.</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
    <message>
        <source>User</source>
        <translation>Utilisateur</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Balles</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Ligne</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Pas d&apos;économiseur d&apos;écran</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Texte</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Temps</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Radio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Serveurs</translation>
    </message>
</context>
<context>
    <name>SplitMode</name>
    <message>
        <source>COOLING</source>
        <translation>Refroidissement</translation>
    </message>
    <message>
        <source>DRY</source>
        <translation>Déshumidificateur</translation>
    </message>
    <message>
        <source>HEATING</source>
        <translation>Chauffage</translation>
    </message>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>FAN</source>
        <translation type="unfinished">Ventilateur</translation>
    </message>
    <message>
        <source>AUTOMATIC</source>
        <translation type="unfinished">Automatique</translation>
    </message>
</context>
<context>
    <name>SplitSettings</name>
    <message>
        <source>SWING</source>
        <translation>Oscillation</translation>
    </message>
</context>
<context>
    <name>SplitSpeed</name>
    <message>
        <source>HIGH</source>
        <translation>Haute</translation>
    </message>
    <message>
        <source>LOW</source>
        <translation>Basse</translation>
    </message>
    <message>
        <source>MEDIUM</source>
        <translation>Moyenne</translation>
    </message>
    <message>
        <source>SILENT</source>
        <translation>Silencieux</translation>
    </message>
    <message>
        <source>AUTOMATIC</source>
        <translation type="unfinished">Automatique</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>En service</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Autotest</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Contrôle</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>12 derniers mois</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Serrure</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Lum. Escaliers</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Inconnu</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
