<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>всегда</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>пон-пят</translation>
    </message>
    <message>
        <source>once</source>
        <translation>однажды</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>суб-воскр</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>срочный вызов</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Вторжение</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>самозащита</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>технич.тревога</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Сильная яркость</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Слабая яркость</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Выкл.</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Нажмите crosshair</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Нажмите кнопку ОК</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>яркость</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Калибровка</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Почистить экран</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Заставка экрана</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Потребление</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Производство</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/дней</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/часов</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/месяцев</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Накопительная</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Текущая</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Среднедневная</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>День</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Час</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Месяц</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Ручной</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>ПАРОЛЬ:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Портал</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Маска подсети</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Альбом:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Артист:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Время:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>из</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Дорожка:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Баланс</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Низкие</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Громко</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Высокие</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Классический</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Танцевальный</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Низкие</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Высокие</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Нормальный</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Вечеринка</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Поп</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Настройка</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Рок</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Спокойный</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Техно</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Шарики</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Деформация</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Линия</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Нет заставки экрана</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Текст</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Время</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>Servers</source>
        <translation>Серверы</translation>
    </message>
    <message>
        <source>IP Radio</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Активировать</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Самоанализ</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Тест</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Последние 12 месяцев</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Замок</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Свет лестница</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Неизвестный</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
