<!DOCTYPE TS><TS>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>of</source>
        <translation>of</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Track:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artist:</translation>
    </message>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Length:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Treble</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Bass</translation>
    </message>
    <message>
        <source>Balance</source>
        <translation>Balance</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Jazz</source>
        <translation>Jazz</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP Radio</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Self-recluser</source>
        <translation>Self-recluser</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Test</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Self-test</translation>
    </message>
</context>
<context>
    <name>antintrusione</name>
    <message>
        <source>technical</source>
        <translation>technical</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>intrusion</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>tamper</translation>
    </message>
    <message>
        <source>anti-panic</source>
        <translation>anti-panic</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Unknown</source>
        <translation>Unknown</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Staircase light</translation>
    </message>
    <message>
        <source>Door lock</source>
        <translation>Door lock</translation>
    </message>
</context>
<context>
    <name>sveglia</name>
    <message>
        <source>once</source>
        <translation>once</translation>
    </message>
    <message>
        <source>always</source>
        <translation>always</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>mon-fri</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sat-sun</translation>
    </message>
</context>
</TS>
