<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>πάντοτε</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>δευ-παρ</translation>
    </message>
    <message>
        <source>once</source>
        <translation>μια φορά</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>σαβ-κυρ</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>αντι-πανικού</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>παρείσφρυση</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>παρέμβλημα</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>τεχνική</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Υψηλή φωτεινότητα</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Αδύναμη φωτεινότητα</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>κανονικός φωτισμός</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Απενεργοποίηση</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Κάντε κλικ στο σταυρόνημα</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Κάντε κλικ στο κουμπί OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>φωτεινότητα</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Βαθμονόμηση</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Καθαρισμός οθόνης</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Πρόγραμμα προστασίας οθόνης</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Κατανάλωση</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Παραγωγή</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/ημέρες</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/ώρες</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/μήνες</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Αθροιστική (κατανάλωση)</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Ρεύμα</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Ημερήσιος μέσος όρος</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Ημέρα</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Ώρα</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Μήνας</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Χειροκίνητο</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>ΚΩΔΙΚΟΣ:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Πύλη</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Μάσκα υποδικτύου</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>ΆΛΜΠΟΥΜ</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Καλλιτέχνης:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Διάρκεια:</translation>
    </message>
    <message>
        <source>of</source>
        <translation></translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Ίχνος:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Ισοστάθμιση</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Μπάσα</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Δυνατά</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Πρίμα</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Κλασσική</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Χορός</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Πλήρη μπάσα</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Μπάσα στο φουλ</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Κανονικό</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Πάρτι</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Ποπ</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Πρίμα στο φουλ</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Ροκ</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Απαλή</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Τέχνο</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Μπίλιες</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Παραμόρφωση</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Γραμμή</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Δεν υπάρχει πρόγραμμα προστασίας της οθόνης</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Κείμενο</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Χρόνος</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP Ράδιο</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Διακομιστές</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Ενεργοποίηση</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Αυτοδοκιμασία</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Δοκιμασία</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Οι τελευταίοι 12 μήνες</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Κλειδωμένη πόρτα</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Φως της σκάλας</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Άγνωστος</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
