<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>sempre</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>lun-ven</translation>
    </message>
    <message>
        <source>once</source>
        <translation>una volta</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sab-dom</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>antipanico</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Intrusione</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>manomissione</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>tecnico</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Luminosità Alta</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Luminosità Bassa</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Luminosità Normale</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Off</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Premere la croce</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Premere il pulsante OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>Luminosità</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Calibrazione</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Pulisci Schermo</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Salva Schermo</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Consumo</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Produzione</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/giorni</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/ore</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/mesi</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Cumulativo</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Attuale</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Media Giornaliera</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Giorno</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Ora</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Mese</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manuale</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>PASSWORD:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Gateway</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Subnet mask</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artista:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Durata:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>di</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Brano:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Bilanciamento</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Bassi</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Alti</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normale</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Bolle</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Deform</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Linea</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>No Screensaver</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Testo</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Tempo</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Radio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Abilita</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Autotest</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Verifica</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Ultimi 12 mesi</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Serratura</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Luce scala</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Sconosciuto</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
