<!DOCTYPE TS><TS>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>يدوياً</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>of</source>
        <translation>من</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>السكة:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>الفنان:</translation>
    </message>
    <message>
        <source>Album:</source>
        <translation>الألبوم:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>الطول:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Preset</source>
        <translation>ضبط مبدئي</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>ترابل</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>باس</translation>
    </message>
    <message>
        <source>Balance</source>
        <translation>ميزان</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>عالي</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Normal</source>
        <translation>عادي</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>دانس</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>بوب</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>روك</translation>
    </message>
    <message>
        <source>Classical</source>
        <translation>كلاسيك</translation>
    </message>
    <message>
        <source>Jazz</source>
        <translation>جاز</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>بارتي</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>سوفت</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>فول باس</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>فول ترابل</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>ضبط مبدئي</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP راديو</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>الملقم</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Self-recluser</source>
        <translation>اعادة ضبط ذاتي</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>اختبار</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>اختبار ذاتي</translation>
    </message>
</context>
<context>
    <name>antintrusione</name>
    <message>
        <source>technical</source>
        <translation>تقني</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>اقتحام</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>عبثي</translation>
    </message>
    <message>
        <source>anti-panic</source>
        <translation>ضد الذعر</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Unknown</source>
        <translation>غير محدد</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>وميض</translation>
    </message>
    <message>
        <source>Door lock</source>
        <translation>باب مقفل</translation>
    </message>
</context>
<context>
    <name>sveglia</name>
    <message>
        <source>once</source>
        <translation>مرة واحدة</translation>
    </message>
    <message>
        <source>always</source>
        <translation>دائماً</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>اثنين-ثلاثاء</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>سبت-أحد</translation>
    </message>
</context>
</TS>
