<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>zawsze</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>pon-pia</translation>
    </message>
    <message>
        <source>once</source>
        <translation>raz</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sob-nie</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>anty-panika</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>wtargnięcie</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>ingerencja</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>techniczne</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Wysoka jasność</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Niska jasność</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Wył.</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Kliknij krzyżyk</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Kliknij przycisk OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>jasność</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Kalibracja</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Czysty ekran</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Wygaszacz ekranu</translation>
    </message>
</context>
<context>
    <name>EnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Pobór</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Produkcja</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/dni</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/godziny</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/miesiące</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Łącznie</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Prąd</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Średnia dzienna</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Dzień</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Godzina</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Miesiąc</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Ręczny</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>HASŁO:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Wejście</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Maska podsieci</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artysta:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Długość:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>/</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Utwór:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balans</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Basy</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Głośny</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Soprany</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Klasyczna</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Pełne basy</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Pełne soprany</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normalny</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Nastawianie</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Miękki</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Piłki</translation>
    </message>
    <message>
        <source>Deform</source>
        <translation>Deformacja</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Linia</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Bez wygaszacza ekranu</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Tekst</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Czas</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Radio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Serwery</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Uaktywnij</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Auto-test</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Test</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Ostatnich 12 miesięcy</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Zamek drzwi</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Oświetlenie schodów</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Nieznany</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
