<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="hr" sourcelanguage="en">
<context>
    <name>AlarmClock</name>
    <message>
        <source>always</source>
        <translation>uvijek</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>pon-pet</translation>
    </message>
    <message>
        <source>once</source>
        <translation>jedanput</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sub-ned</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>protiv panike</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Nedopušteni ulazak</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>nedopušteno manipuliranje</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>tehnički</translation>
    </message>
</context>
<context>
    <name>BrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>Visoka jačina osvjetljenja</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>Niska jačina osvjetljenja</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>Normalna jačina osvjetljenja</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>Isključeno</translation>
    </message>
</context>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation>Klikni ciljnik</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>Klikni gumb OK</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>Jačina osvjetljenja</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>Kalibracija</translation>
    </message>
    <message>
        <source>Clean Screen</source>
        <translation>Čist zaslon</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>Čuvar zaslona</translation>
    </message>
</context>
<context>
    <name>EditEnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>Potrošnja</translation>
    </message>
    <message>
        <source>DHW</source>
        <translation>DHW</translation>
    </message>
    <message>
        <source>Electricity</source>
        <translation>Struja</translation>
    </message>
    <message>
        <source>Gas</source>
        <translation>Gorivo</translation>
    </message>
    <message>
        <source>Heating/Cooling</source>
        <translation>Grijanje/hlađenje</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>Produkcija</translation>
    </message>
    <message>
        <source>Water</source>
        <translation>Voda</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/dani</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/sati</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/mjeseci</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>Kumulativno</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>Trenutno</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>Dnevni prosjek</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>Dan</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>Sat</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>Mjesec</translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Priručnik</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>LOZINKA:</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>DNS</source>
        <translation>DNS</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>Pristupnik</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>Maska podmreže</translation>
    </message>
</context>
<context>
    <name>LoadDataContent</name>
    <message>
        <source>date/time</source>
        <translation>DATUM/SAT</translation>
    </message>
</context>
<context>
    <name>LoadDataPage</name>
    <message>
        <source>Text-Confirm-LoadDataPage</source>
        <translation type="unfinished">Pohranjeni podaci će biti izbrisani.
U redu za potvrdu.</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Izvođač:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Duljina:</translation>
    </message>
    <message>
        <source>of</source>
        <translation>od</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Zapis:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Balance</source>
        <translation>Balans</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Bas</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Glasno</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Treble</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>Klasika</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Ples</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Puni bas</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Puni treble</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>Normalno</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Nježno</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Tehno</translation>
    </message>
    <message>
        <source>User</source>
        <translation>Korisnik</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>Bal</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>Linija</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>Nema čuvara zaslona</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>Tekst</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>Sat</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP radio</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Poslužitelji</translation>
    </message>
</context>
<context>
    <name>SplitMode</name>
    <message>
        <source>COOLING</source>
        <translation>Hlađenje</translation>
    </message>
    <message>
        <source>DRY</source>
        <translation>Suh</translation>
    </message>
    <message>
        <source>HEATING</source>
        <translation>Grijanje</translation>
    </message>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>FAN</source>
        <translation>Ventilator</translation>
    </message>
    <message>
        <source>AUTOMATIC</source>
        <translation>Automatski</translation>
    </message>
</context>
<context>
    <name>SplitSettings</name>
    <message>
        <source>SWING</source>
        <translation>Okretanje</translation>
    </message>
</context>
<context>
    <name>SplitSpeed</name>
    <message>
        <source>HIGH</source>
        <translation>Visina</translation>
    </message>
    <message>
        <source>LOW</source>
        <translation>Nisko </translation>
    </message>
    <message>
        <source>MEDIUM</source>
        <translation>Medij</translation>
    </message>
    <message>
        <source>SILENT</source>
        <translation>Tiho</translation>
    </message>
    <message>
        <source>AUTOMATIC</source>
        <translation>Automatski</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Enable</source>
        <translation>Omogući</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Samoispitivanje</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Ispitivanje</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>Posljednjih 12 mjeseci</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Door lock</source>
        <translation>Brava na vratima</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Stubišno svjetlo</translation>
    </message>
    <message>
        <source>Unknown</source>
        <translation>Nepoznato</translation>
    </message>
</context>
<context>
    <name>device_condition</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_aux</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_dimming_100</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
</context>
<context>
    <name>device_condition_light_status</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
<context>
    <name>device_condition_volume</name>
    <message>
        <source>OFF</source>
        <translation>OFF</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>ON</translation>
    </message>
</context>
</TS>
