<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="zh" sourcelanguage="en">
<context>
    <name>AlarmClockDays</name>
    <message>
        <source>Friday</source>
        <translation>星期五</translation>
    </message>
    <message>
        <source>Monday</source>
        <translation>星期一</translation>
    </message>
    <message>
        <source>Once</source>
        <translation>一次</translation>
    </message>
    <message>
        <source>Saturday</source>
        <translation>星期六</translation>
    </message>
    <message>
        <source>Sunday</source>
        <translation>星期日</translation>
    </message>
    <message>
        <source>Thursday</source>
        <translation>星期四</translation>
    </message>
    <message>
        <source>Tuesday</source>
        <translation>星期二</translation>
    </message>
    <message>
        <source>Wednesday</source>
        <translation>星期三</translation>
    </message>
</context>
<context>
    <name>AlarmClockTimeDays</name>
    <message>
        <source>Fri</source>
        <translation>星期五</translation>
    </message>
    <message>
        <source>Mon</source>
        <translation>星期一</translation>
    </message>
    <message>
        <source>Sat</source>
        <translation>星期六</translation>
    </message>
    <message>
        <source>Sun</source>
        <translation>星期日</translation>
    </message>
    <message>
        <source>Thu</source>
        <translation>星期四</translation>
    </message>
    <message>
        <source>Tue</source>
        <translation>星期二</translation>
    </message>
    <message>
        <source>Wake up</source>
        <translation>叫醒</translation>
    </message>
    <message>
        <source>Wed</source>
        <translation>星期三</translation>
    </message>
</context>
<context>
    <name>AlarmListPage</name>
    <message>
        <source>Alarm type</source>
        <translation>警报类型</translation>
    </message>
    <message>
        <source>Alarms</source>
        <translation>报警</translation>
    </message>
    <message>
        <source>Date &amp; Hour</source>
        <translation>日期和小时</translation>
    </message>
    <message>
        <source>Zone</source>
        <translation>区</translation>
    </message>
</context>
<context>
    <name>AlarmPage</name>
    <message>
        <source>Date</source>
        <translation>日期</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>小时</translation>
    </message>
    <message>
        <source>Zone</source>
        <translation>区</translation>
    </message>
</context>
<context>
    <name>Antintrusion</name>
    <message>
        <source>anti-panic</source>
        <translation>免惊慌</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>侵入</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>防拆</translation>
    </message>
    <message>
        <source>technical</source>
        <translation>技术</translation>
    </message>
    <message>
        <source>Z%1</source>
        <translation>Z%1</translation>
    </message>
</context>
<context>
    <name>AudioPlayerPage</name>
    <message>
        <source>Album:</source>
        <translation>专辑:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>艺术家:</translation>
    </message>
    <message>
        <source>Information not available</source>
        <translation>信息不可用</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>长度:</translation>
    </message>
    <message>
        <source>Loading...</source>
        <translation>加载...</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>曲目表:</translation>
    </message>
</context>
<context>
    <name>CalibrationWidget</name>
    <message>
        <source>Click the crosshair</source>
        <translation>按一下十字</translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation>点击OK按钮</translation>
    </message>
</context>
<context>
    <name>CallNotifierPage</name>
    <message>
        <source>Door lock</source>
        <translation>门锁</translation>
    </message>
</context>
<context>
    <name>DeviceConditionDisplayDimming</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>DeviceConditionDisplayOnOff</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>开启</translation>
    </message>
</context>
<context>
    <name>DeviceConditionDisplayVolume</name>
    <message>
        <source>OFF</source>
        <translation>关闭</translation>
    </message>
    <message>
        <source>ON</source>
        <translation>开启</translation>
    </message>
</context>
<context>
    <name>DisplayPage</name>
    <message>
        <source>Brightness</source>
        <translation>亮度</translation>
    </message>
    <message>
        <source>Calibration</source>
        <translation>校准</translation>
    </message>
    <message>
        <source>Screen Saver</source>
        <translation>屏幕保护程序</translation>
    </message>
</context>
<context>
    <name>EditEnergyCost</name>
    <message>
        <source>Consumption</source>
        <translation>消耗</translation>
    </message>
    <message>
        <source>DHW</source>
        <translation>DHW</translation>
    </message>
    <message>
        <source>Electricity</source>
        <translation>电</translation>
    </message>
    <message>
        <source>Gas</source>
        <translation>燃气</translation>
    </message>
    <message>
        <source>Heating/Cooling</source>
        <translation>加热/制冷</translation>
    </message>
    <message>
        <source>Production</source>
        <translation>发电</translation>
    </message>
    <message>
        <source>Water</source>
        <translation>水</translation>
    </message>
</context>
<context>
    <name>EnergyView</name>
    <message>
        <source>/days</source>
        <translation>/日</translation>
    </message>
    <message>
        <source>/hours</source>
        <translation>/小时</translation>
    </message>
    <message>
        <source>/months</source>
        <translation>/月</translation>
    </message>
    <message>
        <source>Cumulative</source>
        <translation>累加</translation>
    </message>
    <message>
        <source>Current</source>
        <translation>当前</translation>
    </message>
    <message>
        <source>Daily Average</source>
        <translation>日平均</translation>
    </message>
    <message>
        <source>Day</source>
        <translation>天</translation>
    </message>
    <message>
        <source>Hour</source>
        <translation>小时</translation>
    </message>
    <message>
        <source>Month</source>
        <translation>月</translation>
    </message>
</context>
<context>
    <name>FeedItemWidget</name>
    <message>
        <source>No description</source>
        <translation>没有描述</translation>
    </message>
</context>
<context>
    <name>HandsFree</name>
    <message>
        <source>Hands Free</source>
        <translation>免提</translation>
    </message>
</context>
<context>
    <name>InactiveBrightnessPage</name>
    <message>
        <source>High brightness</source>
        <translation>高等亮度</translation>
    </message>
    <message>
        <source>Low brightness</source>
        <translation>低等亮度</translation>
    </message>
    <message>
        <source>Normal brightness</source>
        <translation>正常亮度</translation>
    </message>
    <message>
        <source>Off</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>Keypad</name>
    <message>
        <source>PASSWORD:</source>
        <translation>密码:</translation>
    </message>
    <message>
        <source>Wrong password</source>
        <translation>密码错误</translation>
    </message>
</context>
<context>
    <name>LanSettings</name>
    <message>
        <source>Connection Status</source>
        <translation>连接状态</translation>
    </message>
    <message>
        <source>DNS</source>
        <translation>域名系统</translation>
    </message>
    <message>
        <source>Down</source>
        <translation>下</translation>
    </message>
    <message>
        <source>Gateway</source>
        <translation>网关</translation>
    </message>
    <message>
        <source>IP</source>
        <translation>IP</translation>
    </message>
    <message>
        <source>Mac</source>
        <translation>Mac</translation>
    </message>
    <message>
        <source>Subnet mask</source>
        <translation>子网掩码</translation>
    </message>
    <message>
        <source>Up</source>
        <translation>上</translation>
    </message>
</context>
<context>
    <name>MultimediaContainer</name>
    <message>
        <source>IP Radio</source>
        <translation>IP广播</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>服务器</translation>
    </message>
</context>
<context>
    <name>MultimediaFileListPage</name>
    <message>
        <source>Folder</source>
        <translation>文件夹</translation>
    </message>
</context>
<context>
    <name>PasswordChanger</name>
    <message>
        <source>Check password:</source>
        <translation>验证密码：</translation>
    </message>
    <message>
        <source>New password:</source>
        <translation>新密码：</translation>
    </message>
    <message>
        <source>Old password:</source>
        <translation>旧密码：</translation>
    </message>
    <message>
        <source>Verify password:</source>
        <translation>检验密码：</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPage</name>
    <message>
        <source>Balance</source>
        <translation>平衡</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>低音</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>响亮</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>高音</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Classical</source>
        <translation>古典</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>舞曲</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>重低音</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>重高音</translation>
    </message>
    <message>
        <source>Normal</source>
        <translation>正常</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>宴会</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>流行</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>摇滚</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>轻音乐</translation>
    </message>
    <message>
        <source>Techno</source>
        <translation>Techno音乐</translation>
    </message>
    <message>
        <source>User</source>
        <translation>用户</translation>
    </message>
</context>
<context>
    <name>ProbesPage</name>
    <message>
        <source>Probe</source>
        <translation>传感器</translation>
    </message>
    <message>
        <source>Temperature</source>
        <translation>温度</translation>
    </message>
    <message>
        <source>Zone</source>
        <translation>区</translation>
    </message>
</context>
<context>
    <name>ProfessionalStudio</name>
    <message>
        <source>Professional studio</source>
        <translation>专业工作室</translation>
    </message>
</context>
<context>
    <name>RadioInfo</name>
    <message>
        <source>Channel: %1</source>
        <translation>通道：%1</translation>
    </message>
    <message>
        <source>FM %1</source>
        <translation>FM%1</translation>
    </message>
</context>
<context>
    <name>RadioPage</name>
    <message>
        <source>RDS Radio</source>
        <translation>RDS广播</translation>
    </message>
</context>
<context>
    <name>ScreenSaverPage</name>
    <message>
        <source>Balls</source>
        <translation>球式屏幕保护程序</translation>
    </message>
    <message>
        <source>Line</source>
        <translation>线条</translation>
    </message>
    <message>
        <source>No screensaver</source>
        <translation>无屏幕保护程序</translation>
    </message>
    <message>
        <source>Slideshow</source>
        <translation>幻灯片播放</translation>
    </message>
    <message>
        <source>Slideshow timeout</source>
        <translation>幻灯片播放暂停</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>文字内容</translation>
    </message>
    <message>
        <source>Time</source>
        <translation>小时</translation>
    </message>
</context>
<context>
    <name>ScreensaverTiming</name>
    <message>
        <source> sec</source>
        <translation>秒</translation>
    </message>
</context>
<context>
    <name>SlideshowSelector</name>
    <message>
        <source>Folder</source>
        <translation>文件夹</translation>
    </message>
</context>
<context>
    <name>SplitMode</name>
    <message>
        <source>AUTOMATIC</source>
        <translation type="unfinished">自动</translation>
    </message>
    <message>
        <source>FAN</source>
        <translation type="unfinished">风扇</translation>
    </message>
    <message>
        <source>HEATING</source>
        <translation type="unfinished">供暖</translation>
    </message>
    <message>
        <source>OFF</source>
        <translation type="unfinished">关闭</translation>
    </message>
    <message>
        <source>COOLING</source>
        <translation type="unfinished">降温</translation>
    </message>
</context>
<context>
    <name>SplitPage</name>
    <message>
        <source>Off</source>
        <translation>关闭</translation>
    </message>
</context>
<context>
    <name>SplitSpeed</name>
    <message>
        <source>AUTOMATIC</source>
        <translation type="unfinished">自动</translation>
    </message>
    <message>
        <source>LOW</source>
        <translation type="unfinished">低</translation>
    </message>
    <message>
        <source>MEDIUM</source>
        <translation type="unfinished">中</translation>
    </message>
    <message>
        <source>SILENT</source>
        <translation type="unfinished">无声</translation>
    </message>
    <message>
        <source>HIGH</source>
        <translation type="unfinished">High</translation>
    </message>
</context>
<context>
    <name>StopAndGoBTestPage</name>
    <message>
        <source>Enable</source>
        <translation>启动</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>自测</translation>
    </message>
</context>
<context>
    <name>StopAndGoPage</name>
    <message>
        <source>Enable</source>
        <translation>启动</translation>
    </message>
</context>
<context>
    <name>StopAndGoPlusPage</name>
    <message>
        <source>Enable</source>
        <translation>启动</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>测试</translation>
    </message>
</context>
<context>
    <name>TimePeriodSelection</name>
    <message>
        <source>Last 12 months</source>
        <translation>最后12个月</translation>
    </message>
</context>
<context>
    <name>TransitionEffects</name>
    <message>
        <source>Enlarge</source>
        <translation>放大</translation>
    </message>
    <message>
        <source>None</source>
        <translation>无</translation>
    </message>
</context>
<context>
    <name>VideoDoorEntry</name>
    <message>
        <source>Unknown</source>
        <translation>未知</translation>
    </message>
</context>
</TS>
