<!DOCTYPE TS><TS>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>手动</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>of</source>
        <translation>在</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>曲目表:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>艺术家:</translation>
    </message>
    <message>
        <source>Album:</source>
        <translation>专辑:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>长度:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Preset</source>
        <translation>预设</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>高音</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>低音</translation>
    </message>
    <message>
        <source>Balance</source>
        <translation>平衡</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>响亮</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Normal</source>
        <translation>正常</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>舞曲</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>流行</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>摇滚</translation>
    </message>
    <message>
        <source>Classical</source>
        <translation>古典</translation>
    </message>
    <message>
        <source>Jazz</source>
        <translation>爵士</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>宴会</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>轻音乐</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>重低音</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>重高音</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>预设</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>网络广播</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>服务器</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Self-recluser</source>
        <translation>自动重启</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>测试</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>自测</translation>
    </message>
</context>
<context>
    <name>antintrusione</name>
    <message>
        <source>technical</source>
        <translation>技术</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>入侵</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>防拆</translation>
    </message>
    <message>
        <source>anti-panic</source>
        <translation>免惊慌</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Unknown</source>
        <translation>未知</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>楼梯灯</translation>
    </message>
    <message>
        <source>Door lock</source>
        <translation>门锁</translation>
    </message>
</context>
<context>
    <name>sveglia</name>
    <message>
        <source>once</source>
        <translation>一次</translation>
    </message>
    <message>
        <source>always</source>
        <translation>永远</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>周一至周五</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>周六至周日</translation>
    </message>
</context>
<context>
    <name>tastiera</name>
    <message>
        <source>PASSWORD:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
