<!DOCTYPE TS><TS>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click here!</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manual</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>of</source>
        <translation>de</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation>Tema:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Artista:</translation>
    </message>
    <message>
        <source>Album:</source>
        <translation>Álbum:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Duración:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Altos</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Bajos</translation>
    </message>
    <message>
        <source>Balance</source>
        <translation>Balanceado</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Jazz</source>
        <translation>Jazz</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>IP Radio</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servidores</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Self-recluser</source>
        <translation>Reset</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Verificar</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Autotest</translation>
    </message>
</context>
<context>
    <name>antintrusione</name>
    <message>
        <source>technical</source>
        <translation>técnica</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>antirrobo</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>manipulación</translation>
    </message>
    <message>
        <source>anti-panic</source>
        <translation>antipánico</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Unknown</source>
        <translation>Desconocido</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Luz escaleras</translation>
    </message>
    <message>
        <source>Door lock</source>
        <translation>Cerradura</translation>
    </message>
</context>
<context>
    <name>sveglia</name>
    <message>
        <source>once</source>
        <translation>una vez</translation>
    </message>
    <message>
        <source>always</source>
        <translation>siempre</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>lun-ven</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>sab-dom</translation>
    </message>
</context>
<context>
    <name>tastiera</name>
    <message>
        <source>PASSWORD:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
