<!DOCTYPE TS><TS>
<context>
    <name>Calibrate</name>
    <message>
        <source>Click the crosshair</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Click the OK button</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>FSBannManual</name>
    <message>
        <source>Manual</source>
        <translation>Manuell</translation>
    </message>
</context>
<context>
    <name>MediaPlayWindow</name>
    <message>
        <source>of</source>
        <translation>von</translation>
    </message>
    <message>
        <source>Track:</source>
        <translation type="unfinished">Musikst.:</translation>
    </message>
    <message>
        <source>Artist:</source>
        <translation>Künstler:</translation>
    </message>
    <message>
        <source>Album:</source>
        <translation>Album:</translation>
    </message>
    <message>
        <source>Length:</source>
        <translation>Dauer:</translation>
    </message>
</context>
<context>
    <name>PowerAmplifier</name>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
    <message>
        <source>Treble</source>
        <translation>Hoch</translation>
    </message>
    <message>
        <source>Bass</source>
        <translation>Teif</translation>
    </message>
    <message>
        <source>Balance</source>
        <translation>Ausgleich</translation>
    </message>
    <message>
        <source>Loud</source>
        <translation>Loud</translation>
    </message>
</context>
<context>
    <name>PowerAmplifierPreset</name>
    <message>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <source>Dance</source>
        <translation>Dance</translation>
    </message>
    <message>
        <source>Pop</source>
        <translation>Pop</translation>
    </message>
    <message>
        <source>Rock</source>
        <translation>Rock</translation>
    </message>
    <message>
        <source>Classical</source>
        <translation>Classical</translation>
    </message>
    <message>
        <source>Jazz</source>
        <translation>Jazz</translation>
    </message>
    <message>
        <source>Party</source>
        <translation>Party</translation>
    </message>
    <message>
        <source>Soft</source>
        <translation>Soft</translation>
    </message>
    <message>
        <source>Full Bass</source>
        <translation>Full Bass</translation>
    </message>
    <message>
        <source>Full Treble</source>
        <translation>Full Treble</translation>
    </message>
    <message>
        <source>Preset</source>
        <translation>Preset</translation>
    </message>
</context>
<context>
    <name>SourceChoice</name>
    <message>
        <source>IP Radio</source>
        <translation>Radio IP</translation>
    </message>
    <message>
        <source>Servers</source>
        <translation>Servers</translation>
    </message>
</context>
<context>
    <name>StopngoPage</name>
    <message>
        <source>Self-recluser</source>
        <translation>Reset</translation>
    </message>
    <message>
        <source>Test</source>
        <translation>Test</translation>
    </message>
    <message>
        <source>Self-test</source>
        <translation>Auto Test</translation>
    </message>
</context>
<context>
    <name>antintrusione</name>
    <message>
        <source>technical</source>
        <translation>Technik</translation>
    </message>
    <message>
        <source>intrusion</source>
        <translation>Einbruch</translation>
    </message>
    <message>
        <source>tamper</source>
        <translation>Aufbruch</translation>
    </message>
    <message>
        <source>anti-panic</source>
        <translation>Antipanik</translation>
    </message>
</context>
<context>
    <name>call_notifier</name>
    <message>
        <source>Unknown</source>
        <translation>Unbekannt</translation>
    </message>
    <message>
        <source>Staircase light</source>
        <translation>Treppenlicht</translation>
    </message>
    <message>
        <source>Door lock</source>
        <translation>Schloss</translation>
    </message>
</context>
<context>
    <name>sveglia</name>
    <message>
        <source>once</source>
        <translation>ein Mal</translation>
    </message>
    <message>
        <source>always</source>
        <translation>immer</translation>
    </message>
    <message>
        <source>mon-fri</source>
        <translation>Mon-Fr</translation>
    </message>
    <message>
        <source>sat-sun</source>
        <translation>Sam-Son</translation>
    </message>
</context>
<context>
    <name>tastiera</name>
    <message>
        <source>PASSWORD:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
